entity.product.settings:
  title: Product
  description: Configure a Product entity type
  route_name:  entity.product.settings
  parent: system.admin_structure
entity.product.collection:
  title: Products
  description: List of products
  route_name: entity.product.collection
  parent: system.admin_content
entity.importer.overview:
  title: Importers
  parent: system.admin_structure
  description: 'List of importers to extend site functionality.'
  route_name: entity.importer.collection
